// Generated by gencpp from file sc_msgs/GetParamListRequest.msg
// DO NOT EDIT!


#ifndef SC_MSGS_MESSAGE_GETPARAMLISTREQUEST_H
#define SC_MSGS_MESSAGE_GETPARAMLISTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sc_msgs
{
template <class ContainerAllocator>
struct GetParamListRequest_
{
  typedef GetParamListRequest_<ContainerAllocator> Type;

  GetParamListRequest_()
    {
    }
  GetParamListRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::sc_msgs::GetParamListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sc_msgs::GetParamListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetParamListRequest_

typedef ::sc_msgs::GetParamListRequest_<std::allocator<void> > GetParamListRequest;

typedef boost::shared_ptr< ::sc_msgs::GetParamListRequest > GetParamListRequestPtr;
typedef boost::shared_ptr< ::sc_msgs::GetParamListRequest const> GetParamListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sc_msgs::GetParamListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sc_msgs::GetParamListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace sc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sc_msgs::GetParamListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sc_msgs::GetParamListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sc_msgs::GetParamListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sc_msgs::GetParamListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sc_msgs::GetParamListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sc_msgs::GetParamListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sc_msgs::GetParamListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sc_msgs::GetParamListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::sc_msgs::GetParamListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sc_msgs/GetParamListRequest";
  }

  static const char* value(const ::sc_msgs::GetParamListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sc_msgs::GetParamListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::sc_msgs::GetParamListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sc_msgs::GetParamListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetParamListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sc_msgs::GetParamListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::sc_msgs::GetParamListRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SC_MSGS_MESSAGE_GETPARAMLISTREQUEST_H
